### ISSUE TITLE
About

### ISSUE THREAD

**Issue by SeiniTetsuko** [GalaxyCong/HPMDubbing#2]
I tried to download the movies from the link which is provied in V2C. All the movies seems to be protected and they can't be edited.

**Comment by WentuHua007** [comment]
感谢，邮件已收到～

**Comment by maxwell00t6** [comment]
感谢，邮件已收到～

**Comment by GalaxyCong** [comment]
I'm sorry about the [issues](https://github.com/chenqi008/V2C/issues/3) with the raw movie downloads from the V2C link (https://github.com/chenqi008/V2C/issues/3). You can download our preprocessed features first.
