### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by XiaoYuanJun-zy** [GalaxyCong/HPMDubbing#4]
非常优秀的工作，但是
 我在用作者提供的预训练模型来合成音频时，几乎全是电流，这是为什么呢？
Mel图直接崩了。
这是val set合成出的音频：![image](https://github.com/GalaxyCong/HPMDubbing/assets/69071903/514bffa3-11aa-4297-b121-35f81c225bd7)
这是使用的预训练参数：
![image](https://github.com/GalaxyCong/HPMDubbing/assets/69071903/ca64f1b6-be1d-492c-9c31-25d719f7c0f3)

后面，我自己重新训使用作者提供的预处理好的特征去重新训了模型，这是在30000步保存的模型合成的结果。
![image](https://github.com/GalaxyCong/HPMDubbing/assets/69071903/b8030314-ce05-4d4c-963f-f100dcd7bf9f)
![image](https://github.com/GalaxyCong/HPMDubbing/assets/69071903/f9875b93-a7d1-4a06-b169-a5146a559d91)

效果虽然还不行，但是至少不是全是电流音。

**Comment by issuer2002** [comment]
我也出现了这个问题，效果很差另外我想问问答主没有没尝试提取Chem数据集的特征，或者别的数据集的特征进行训练》

**Comment by GalaxyCong** [comment]
大家好～我明天检查一下问题。好的，没问题chem数据集的特征我也尽快上传～

**Comment by issuer2002** [comment]
> **之前整理地有些仓促模型缺失了一些细节和checkpoint不匹配造成电音现象，我们这几天会仔细检查尽快更新出正确的版本。** 我们会提供V2C和Chem两个数据集的pretrain model帮助您正常完成inference, 非常感谢您的关注，请您注意更新如果还有问题可以随时和我联系～ [Chem数据集](https://pan.baidu.com/s/13hYDfTHvjuz8qEk6Gn0lRA)的特征已上传完成，密码chem～

如果方便的话 希望能将数据特征提取的步骤再详细写下，想要学习下

**Comment by GalaxyCong** [comment]
> > **之前整理地有些仓促模型缺失了一些细节和checkpoint不匹配造成电音现象，我们这几天会仔细检查尽快更新出正确的版本。** 我们会提供V2C和Chem两个数据集的pretrain model帮助您正常完成inference, 非常感谢您的关注，请您注意更新如果还有问题可以随时和我联系～ [Chem数据集](https://pan.baidu.com/s/13hYDfTHvjuz8qEk6Gn0lRA)的特征已上传完成，密码chem～
> 
> 如果方便的话 希望能将数据特征提取的步骤再详细写下，想要学习下

好的～我们会提供更加详细地处理流程

**Comment by XiaoYuanJun-zy** [comment]
> **之前整理地有些仓促模型缺失了一些细节和checkpoint不匹配造成电音现象，我们这几天会仔细检查尽快更新出正确的版本。** 我们会提供V2C和Chem两个数据集的pretrain model帮助您正常完成inference, 非常感谢您的关注，请您注意更新如果还有问题可以随时和我联系～ [Chem数据集](https://pan.baidu.com/s/13hYDfTHvjuz8qEk6Gn0lRA)的特征已上传完成，密码chem～

感谢作者您在百忙之中解决我们遇到的问题.
这是我自己训练的模型，作者您那里训练到最后total loss大概是多少呢？
![image](https://github.com/GalaxyCong/HPMDubbing/assets/69071903/579bcdf4-ae64-479d-9780-810fd8a8f43d)
![image](https://github.com/GalaxyCong/HPMDubbing/assets/69071903/0e82c34d-18dd-4b59-a6b9-c62079357797)

**Comment by issuer2002** [comment]
> > **之前整理地有些仓促模型缺失了一些细节和checkpoint不匹配造成电音现象，我们这几天会仔细检查尽快更新出正确的版本。** 我们会提供V2C和Chem两个数据集的pretrain model帮助您正常完成inference, 非常感谢您的关注，请您注意更新如果还有问题可以随时和我联系～ [Chem数据集](https://pan.baidu.com/s/13hYDfTHvjuz8qEk6Gn0lRA)的特征已上传完成，密码chem～
> 
> 感谢作者您在百忙之中解决我们遇到的问题. 这是我自己训练的模型，作者您那里训练到最后total loss大概是多少呢？ ![image](https://user-images.githubusercontent.com/69071903/282294816-579bcdf4-ae64-479d-9780-810fd8a8f43d.png) ![image](https://user-images.githubusercontent.com/69071903/282294828-0e82c34d-18dd-4b59-a6b9-c62079357797.png)

我在chem特征训练了下，total loss如下：
![image](https://github.com/GalaxyCong/HPMDubbing/assets/149258163/1e21e899-fa03-4931-866e-40409a0c59d9)

**Comment by GalaxyCong** [comment]
<img width="1512" alt="image" src="https://github.com/GalaxyCong/HPMDubbing/assets/109259667/d8c69818-27e0-4a83-9a2f-3fc756a09655">
<img width="1508" alt="image" src="https://github.com/GalaxyCong/HPMDubbing/assets/109259667/70f6c9e3-3c54-421e-a7f7-7b4a2672429c">

Hello，XiaoYuan, issuer2002 抱歉回复的太迟，chem数据集的loss大约在1.7左右，V2C的loss在2.5左右，参数需要略微调整一下，老的版本缺失了一些细节，给您造成困扰还望谅解

**Comment by XiaoYuanJun-zy** [comment]
> <img alt="image" width="1512" src="https://user-images.githubusercontent.com/109259667/283358419-d8c69818-27e0-4a83-9a2f-3fc756a09655.png"> <img alt="image" width="1508" src="https://user-images.githubusercontent.com/109259667/283359526-70f6c9e3-3c54-421e-a7f7-7b4a2672429c.png">
> Hello，XiaoYuan, issuer2002 抱歉回复的太迟，chem数据集的loss大约在1.7左右，V2C的loss在2.5左右，参数需要略微调整一下，老的版本缺失了一些细节，给您造成困扰还望谅解

好哒，特别感谢您的真诚回复。我再重新调整一下参数试试。

**Comment by issuer2002** [comment]
> > > **之前整理地有些仓促模型缺失了一些细节和checkpoint不匹配造成电音现象，我们这几天会仔细检查尽快更新出正确的版本。** 我们会提供V2C和Chem两个数据集的pretrain model帮助您正常完成inference, 非常感谢您的关注，请您注意更新如果还有问题可以随时和我联系～ [Chem数据集](https://pan.baidu.com/s/13hYDfTHvjuz8qEk6Gn0lRA)的特征已上传完成，密码chem～
> > 
> > 
> > 如果方便的话 希望能将数据特征提取的步骤再详细写下，想要学习下
> 
> 好的～我们会提供更加详细地处理流程

请问作者什么时间能更新一下数据特征提取的详细步骤，包括数据准备之类得。很想学习一下，感谢~

**Comment by GalaxyCong** [comment]
> > > > **之前整理地有些仓促模型缺失了一些细节和checkpoint不匹配造成电音现象，我们这几天会仔细检查尽快更新出正确的版本。** 我们会提供V2C和Chem两个数据集的pretrain model帮助您正常完成inference, 非常感谢您的关注，请您注意更新如果还有问题可以随时和我联系～ [Chem数据集](https://pan.baidu.com/s/13hYDfTHvjuz8qEk6Gn0lRA)的特征已上传完成，密码chem～
> > > 
> > > 
> > > 如果方便的话 希望能将数据特征提取的步骤再详细写下，想要学习下
> > 
> > 
> > 好的～我们会提供更加详细地处理流程
> 
> 请问作者什么时间能更新一下数据特征提取的详细步骤，包括数据准备之类得。很想学习一下，感谢~

您好！抱歉回复太迟，还望谅解。大约下周一之前会发给您哈
