### ISSUE TITLE
Chem dataset的特征

### ISSUE THREAD

**Issue by issuer2002** [GalaxyCong/HPMDubbing#5]
Chem dataset提取的特征方便提供一下么？

**Comment by GalaxyCong** [comment]
您好，感谢您的关注。可以的，我会尽快向您提供！

**Comment by issuer2002** [comment]
十分感谢！

**Comment by isxuwl** [comment]
> 您好，感谢您的关注。可以的，我会尽快向您提供！ ![image](https://user-images.githubusercontent.com/109259667/282290234-ed9feb4c-5d16-4ce1-9149-fdbaa63f7fe5.png) 正在上传百度云，今天应该就能下载

请问chem特征的云盘的链接在哪呢？

**Comment by issuer2002** [comment]
> 您好，感谢您的关注。可以的，我会尽快向您提供！ ![image](https://user-images.githubusercontent.com/109259667/282290234-ed9feb4c-5d16-4ce1-9149-fdbaa63f7fe5.png) 正在上传百度云，今天应该就能下载

看到了 感谢！

**Comment by isxuwl** [comment]
已看到~

**Comment by isxuwl** [comment]
已看到~
