### ISSUE TITLE
关于代码的一些细节问题

### ISSUE THREAD

**Issue by XiaoYuanJun-zy** [GalaxyCong/HPMDubbing#6]
作者您好，首先非常感谢您之前的issues解答。看到您最近又更新了code，但是对更新的有些细节暂时还没有看懂。希望可以加您微信，详细请教一下。我的微信号是：Tsukuru-Tazaki
万分感谢您在百忙之中阅读，期待您的回复！

**Comment by GalaxyCong** [comment]
XiaoYuan您好，没问题的，已加您的微信～
